import jsPDF from 'jspdf';

interface ReceiptData {
  transactionId: string;
  date: string;
  userName: string;
  userPhone: string;
  amount: number;
  type: string;
  status: string;
  from?: string;
  to?: string;
}

export const generateReceipt = (data: ReceiptData): void => {
  const pdf = new jsPDF();
  
  // Header
  pdf.setFontSize(20);
  pdf.setTextColor(45, 142, 65); // #2d8e41
  pdf.text('VERMI-FARM', 105, 20, { align: 'center' });
  
  pdf.setFontSize(16);
  pdf.setTextColor(152, 63, 33); // #983F21
  pdf.text('Transaction Receipt', 105, 35, { align: 'center' });
  
  // Line separator
  pdf.setDrawColor(200, 200, 200);
  pdf.line(20, 45, 190, 45);
  
  // Receipt details
  pdf.setFontSize(12);
  pdf.setTextColor(0, 0, 0);
  
  const details = [
    ['Transaction ID:', data.transactionId],
    ['Date & Time:', new Date(data.date).toLocaleString()],
    ['Transaction Type:', data.type],
    ['Status:', data.status],
    ['Amount:', `KES ${data.amount.toLocaleString()}`],
    ['User Name:', data.userName],
    ['Phone Number:', data.userPhone],
  ];

  if (data.from) details.push(['From:', data.from]);
  if (data.to) details.push(['To:', data.to]);

  let yPosition = 60;
  details.forEach(([label, value]) => {
    pdf.setFont('helvetica', 'bold');
    pdf.text(label, 20, yPosition);
    pdf.setFont('helvetica', 'normal');
    pdf.text(value, 80, yPosition);
    yPosition += 10;
  });
  
  // Footer
  yPosition += 20;
  pdf.setDrawColor(200, 200, 200);
  pdf.line(20, yPosition, 190, yPosition);
  
  yPosition += 15;
  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text('This is a computer-generated receipt.', 105, yPosition, { align: 'center' });
  pdf.text('For inquiries, contact support@vermi-farm.org', 105, yPosition + 10, { align: 'center' });
  
  // Download the PDF
  pdf.save(`receipt-${data.transactionId}.pdf`);
};

export const generateCSVReceipt = (data: ReceiptData): void => {
  const csvContent = `Transaction Receipt
Transaction ID,${data.transactionId}
Date & Time,${new Date(data.date).toLocaleString()}
Transaction Type,${data.type}
Status,${data.status}
Amount,KES ${data.amount.toLocaleString()}
User Name,${data.userName}
Phone Number,${data.userPhone}
${data.from ? `From,${data.from}` : ''}
${data.to ? `To,${data.to}` : ''}

Generated by Vermi-Farm System
Contact: support@vermi-farm.org`;

  const blob = new Blob([csvContent], { type: 'text/csv' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `receipt-${data.transactionId}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
};